title: Made By Phil
email: hello@madebyphil.com
description: Minimalist personal site for Phil Heijkoop.
baseurl: ""
url: "https://www.madebyphil.com"  # your GitHub Pages URL
theme: minima

header_pages:
  - index.html
  - blog/index.md
  - about.md